myproject/blog/urls.py
from django.urls import path
from .views import ArticleListView, ArticleDetailView, CategoryListView, AuthorListView, ArticlePreview, SearchList


app_name = 'blog'
urlpatterns = [
    path('', ArticleListView.as_view(), name='index'),
    path('page/<int:page>', ArticleListView.as_view(), name='index'),  # this url for pagination
    path('detail/<slug:slug>/', ArticleDetailView.as_view(), name='article_detail'),
    path('preview/<int:pk>/', ArticlePreview.as_view(), name='article-preview'),
    path('category/<slug:slug>/', CategoryListView.as_view(), name='category_list'),
    path('category/<slug:slug>/page/<int:page>/', CategoryListView.as_view(), name='category_list'),
    path('author/<slug:username>/', AuthorListView.as_view(), name='author_list'),
    path('author/<slug:username>/page/<int:page>/', AuthorListView.as_view(), name='author_list'),
    path('search/', SearchList.as_view(), name='search'),
    path('search/page/<int:page>/', SearchList.as_view(), name='search'),
]

myproject/config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import RedirectView
from account.views import Login, Register, activate

urlpatterns = [
    # path('admin/login/', RedirectView.as_view(url='/login/')),
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('django.contrib.auth.urls')),
    path('register/', Register.as_view(), name='register'),
    # re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='activate'),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
    path('login/', Login.as_view(), name='login'),
    path('account/', include('account.urls')),
    path('comment/', include('comment.urls')),
    path('', include('social_django.urls', namespace='social')),
]

# Serving static files during development
# from django.conf import settings
# from django.conf.urls.static import static
#
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/blog/models.py
from django.db import models
from django.urls import reverse
from account.models import User
from django.utils.html import format_html
from django.utils import timezone
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment


# Create your models here.
# My managers
# This is just for displaying published articles
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')


# This just for displaying active categories
class CategoryManger(models.Manager):
    def active(self):
        return self.filter(status=True)


# Create Category model
class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField(verbose_name='آدرس آیپی')


class Category(models.Model):
    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL, related_name='children', verbose_name='زیر دسته')
    title = models.CharField(max_length=200, verbose_name='عنوان دسته بندی')
    slug = models.CharField(max_length=100, unique=True, verbose_name='آدرس دسته بندی')
    status = models.BooleanField(default=True, verbose_name='آیا دسته بندی نمایش داده شود؟')
    position = models.IntegerField(verbose_name='وضعیت')

    # class meta for making persian language
    class Meta:
        verbose_name = 'دسته بندی '
        verbose_name_plural = 'دسته بندی ها'
        ordering = ['parent__id', 'position']   # We use of parent__id for displaying first parent then children in admin/blog/category.

    # def __str__ for returning objects to string
    def __str__(self):
        return self.title

    objects = CategoryManger()


# Create Article model
class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش نویس'),              # draft
        ('p', 'منتشر شده'),             # published
        ('i', 'در حال بررسی'),          # investigation
        ('b', 'برگشت داده شده'),        # back
    )
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='articles', verbose_name='نویسنده')
    title = models.CharField(max_length=200, verbose_name='عنوان مقاله')
    slug = models.CharField(max_length=100, unique=True, verbose_name='آدرس مقاله')
    # related_name for using in html file
    category = models.ManyToManyField(Category, verbose_name='دسته بندی', related_name='articles')
    description = models.TextField(verbose_name='محتوا')
    thumbnail = models.ImageField(upload_to='images', verbose_name='تصویر مقاله')
    publish = models.DateTimeField(default=timezone.now, verbose_name='زمان انتشار')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_special = models.BooleanField(default=False, verbose_name='مقاله ویژه')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name='وضعیت')
    # This is for comment section.
    comments = GenericRelation(Comment)
    # This relation many to many is for IPAddress
    hits = models.ManyToManyField(IPAddress, through='ArticleHit', blank=True, related_name='hits', verbose_name='بازدیدها')

    # class meta for making persian language
    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقاله ها'
        ordering = ['-publish']

    # def __str__ for returning objects to string
    def __str__(self):
        return self.title

    # we created this def for when we send a article, that it redirects us to index page
    def get_absolute_url(self):
        return reverse('account:index')

    # this is just for displaying published category
    def category_published(self):
        return self.category.filter(status=True)

    # After we wrote manager we must adding to objects
    objects = ArticleManager()

    # For showing thumbnail in admin panel
    def thumbnail_tag(self):
        return format_html("<img src='{}' width=100 height=70 style='border-radius: 5px' ".format(self.thumbnail.url))
    thumbnail_tag.short_description = 'عکس'

    # This def for displaying category in admin panel
    # We can not use category in list_display because it is a list that list_display be able not a list. As result
    # we can use of join method. Point - we can def category_to_str in article model like def __str__ .
    # We can use of obj.category_published() instead of obj.category.all()
    def category_to_str(self):
        return '-'.join([category.title for category in self.category_published()])
    category_to_str.short_description = 'دسته بندی'
    # Important point : we do not need obj object (def category_to_str(self, obj)) here for this reason delete obj (def category_to_str(self))


class ArticleHit(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    ip_address = models.ForeignKey(IPAddress, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

myproject/blog/views.py
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from .models import Article, Category
from account.mixins import AuthorAccessMixin
from account.models import User
from django.db.models import Q


# Create your views here.
# We can use of published() manager instead of Article.objects.filter(status='p')
# def index(request, page=1):
#     article_list = Article.objects.published()
#     paginator = Paginator(article_list, 2)  # Show 2 contacts per page.
#     # page = request.GET.get('page')
#     page_obj = paginator.get_page(page)
#     context = {
#         'articles': page_obj,
#         # 'categories': Category.objects.filter(status=True)
#         # instead of this command we use of templatetags
#     }
#     return render(request, 'blog/article_list.html', context)


# Changed functional index view to class ArticleListView
class ArticleListView(ListView):
    # model = Article    # We do not use of model because we do not want all articles.
    # context_object_name = 'articles'   # We can use of this or use of object_list in html file
    queryset = Article.objects.published()
    # template_name = 'blog/article_list.html'   # We can determine template name or its default name (article_list)
    paginate_by = 2   # For paginating we must use of default content page_obj instead of articles


# We can use of published() manager instead of (Article, slug=slug, status='p')
# def article_detail(request, slug):
#     context = {
#         'article': get_object_or_404(Article.objects.published(), slug=slug)
#     }
#     return render(request, 'blog/article_detail.html', context)


# Changed functional article_detail view to class ArticleDetailView
class ArticleDetailView(DetailView):
    def get_object(self, queryset=None):
        slug = self.kwargs.get('slug')
        article = get_object_or_404(Article.objects.published(), slug=slug)

        ip_address = self.request.user.ip_address
        if ip_address not in article.hits.all():
            article.hits.add(ip_address)

        return article


class ArticlePreview(AuthorAccessMixin, DetailView):
    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Article, pk=pk)


# def category_list(request, slug, page=1):
#     category = get_object_or_404(Category, slug=slug, status=True)
#     article_list = category.articles.published()
#     paginator = Paginator(article_list, 2)  # Show 2 contacts per page.
#     page_obj = paginator.get_page(page)
#     context = {
#         'category': category,
#         'articles': page_obj
#     }
#     return render(request, 'blog/list.html', context)


# Changed functional category_list view to class CategoryListView
class CategoryListView(ListView):
    paginate_by = 2
    template_name = 'blog/category_list.html'

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return category.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context


class AuthorListView(ListView):
    paginate_by = 2
    template_name = 'blog/author_list.html'

    def get_queryset(self):
        global author
        username = self.kwargs.get('username')
        author = get_object_or_404(User, username=username)
        return author.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context


class SearchList(ListView):
    paginate_by = 2
    template_name = 'blog/search_list.html'

    def get_queryset(self):
        search = self.request.GET.get('q')
        return Article.objects.filter(Q(description__icontains=search) | Q(title__icontains=search))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = self.request.GET.get('q')
        return context

myproject/templates/blog/about.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Clean Blog - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="base.html">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="base.html">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="article_detail.html">Sample Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/about-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>About Me</h1>
            <span class="subheading">This is what I do.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="js/clean-blog.min.js"></script>

</body>

</html>

myproject/templates/blog/article_detail.html
{% extends 'blog/base.html' %}
{% load comment_tags %}
{% load ratings %}
{% load base_tags %}
{% load humanize %}


{% load static %}
{% block title %} {{object.title}} {% endblock %}
{% block main_content %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('{{object.thumbnail.url}}')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="post-heading">
                    <h1>{{object.title}}</h1>
                        {% if article.is_special %}
                        <span class="badge badge-danger" style="font-size: 15px">ویژه</span>
                        {% endif %}
                    <time>{{object.publish|naturaltime}}</time>
                    <div>{% ratings object %}</div>
                    <div>بازدیدها : {{object.hits.count}}</div>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Post Content -->
<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto text-justify">
                <aside>
                {% popular_articles %}
                {% hot_articles %}
                </aside>
<!-- we added safe for no showing html tags -->
                {% if object.is_special %}
                    {% if user.is_authenticated and user.is_special_user or user == object.author or user.is_superuser %}
                    {{object.description|safe|linebreaks}}
                    {% else %}
                    {{object.description|striptags|truncatewords:30}}
                    <p class="alert alert-warning">این مقاله ویژه است و باید برای دیدن آن<a class="alert-link" href="#"> اشتراک ویژه </a>داشته باشید.</p>
                    {% endif %}
                {% else %}
                {{object.description|safe|linebreaks}}
                {% endif %}

                {% render_comments object request %}
                {% include_bootstrap %}
            </div>
        </div>
    </div>
</article>
{% endblock %}
<!-- We can use of default context object instead of article -->

myproject/templates/blog/article_list.html
{% extends 'blog/list.html' %}

{% block header %}

{% endblock %}

{% block previous_page_url %}
{% url 'blog:index' page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
{% url 'blog:index' page_obj.next_page_number %}
{% endblock %}

myproject/templates/blog/author_list.html
{% extends 'blog/list.html' %}

{% block header %}
<h3 class="alert alert-primary text-center">{{author.get_full_name}}</h3>
{% endblock %}

{% block previous_page_url %}
{% url 'blog:author_list' author.username page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
{% url 'blog:author_list' author.username page_obj.next_page_number %}
{% endblock %}

myproject/templates/blog/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="fa">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'blog/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'blog/css/clean-blog.min.css' %}" rel="stylesheet">
    <!-- Custom styles for farsi language -->
    <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet">
    <!--  star rating static files  -->
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{% url 'blog:index' %}">{% title %}</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
{% category_navbar %}
    </div>
</nav>

{% block main_content %} {% endblock %}

<hr>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'blog/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'blog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Custom scripts for this template -->
<script src="{% static 'blog/js/clean-blog.min.js' %}"></script>

</body>

</html>

myproject/templates/blog/category_list.html
{% extends 'blog/list.html' %}

{% block header %}
<h3 class="alert alert-primary text-center">{{category.title}}</h3>
{% endblock %}

{% block previous_page_url %}
{% url 'blog:category_list' category.slug page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
{% url 'blog:category_list' category.slug page_obj.next_page_number %}
{% endblock %}

myproject/templates/blog/list.html
{% extends 'blog/base.html' %}
{% load static %}
{% load ratings %}
{% load base_tags %}
{% load humanize %}

{% block title %}Sport News{% endblock %}

{% block main_content %}

<!-- Page Header -->
<header class="masthead" style="background-image: url('{% static "blog/img/home-bg.jpg" %}')">
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
                <h1>اخبار ورزشی</h1>
                <span class="subheading">A Blog Theme by Start Bootstrap</span>
            </div>
        </div>
    </div>
</div>
</header>
<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">

            {% block header %}{% endblock %}

            <aside>
            {% popular_articles %}
            {% hot_articles %}
            </aside>

            {% for article in object_list %}
            <div class="post-preview">
                <a href="{% url 'blog:article_detail' article.slug %}">
                    <h2 class="post-title">
                        {{article.title}}
                        {% if article.is_special %}
                        <span class="badge badge-danger" style="font-size: 15px">ویژه</span>
                        {% endif %}
                    </h2>
                    <div>{% ratings article %}</div>
                    <h3 class="post-subtitle">
                        <!-- we added striptags for no showing html tags -->
                        {{article.description|striptags|truncatewords:30}}
                    </h3>
                </a>
                <p class="post-meta">نوشته شده توسط :
                    <a href="{% url 'blog:author_list' article.author %}">{{article.author.get_full_name}}</a>
                    {{article.publish|naturaltime}}</p>
                <div>
                {% for cat in article.category_published.all %}
                <a href="{% url 'blog:category_list' cat.slug %}">{{cat.title}}</a>
                {% endfor %}
                </div>
                <div>بازدیدها : {{article.hits.count}}</div>
            </div>
            </div>
            <hr>
            {% empty %}
            <p>متاسفانه محتوایی برای نمایش وجود ندارد.</p>
            {% endfor %}
            <!-- Pager -->
            {% if is_paginated %}
            <div class="clearfix">
                {% if page_obj.has_previous %}
                <!-- We can use of this syntax instead of ?page={{articles.previous_page_number}} -->
                <a class="btn btn-primary float-right ml-3" href="{% block previous_page_url %}{% endblock %}">پست های جدید &rarr;</a>
                {% endif %}
                {% if page_obj.has_next %}
                <a class="btn btn-primary float-right" href="{% block next_page_url %}{% endblock %}">پست های قدیمی &larr;</a>
                {% endif %}
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

myproject/templates/blog/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">{% csrf_token %}
    {{form.as_p}}
    <button type="submit">Login</button>
</form>
</body>
</html>

myproject/templates/blog/search_list.html
{% extends 'blog/list.html' %}

{% block header %}
<h3 class="alert alert-primary text-center">{{search}}</h3>
{% endblock %}

{% block previous_page_url %}
{% url 'blog:search'  page_obj.previous_page_number %}?q={{search}}
{% endblock %}

{% block next_page_url %}
{% url 'blog:search'  page_obj.next_page_number %}?q={{search}}
{% endblock %}